### ISSUE TITLE
Emails randomly unverifying

### ISSUE THREAD

**Issue by relative** [pxlblue/backend#2]
Randomly a users emailVerified column in the database may be flipped back to false for no reason

Could be a bug, should look into this lol

**Comment by spline-oss** [comment]
If you were to rub a garlic at the tip of your toe, a few 1 hour after, you will feel the taste in your mouth, this is because the "smelling particles" are tinier and thinner than any other smell particle, they are thin enough to enter your bloodstream starting from your toe and then 1 hour after it will be transported into your tongue. Also, the star Antares is 60,000 times larger than our sun, if our sun was the size of a tennis ball, Antares would be the size of a house, and every year an average of 100 people choke on ballpoint pens and die.

**Comment by relative** [comment]
Not an issue
